src/main/resources/application.properties
=> chore: edit configration

src/main/java/com/example/newsfeed/entity/BaseEntity.java
1. createdAt, modifiedAt 필드로 BaseEntity 생성
=> feat: BaseEntity 생성

src/main/java/com/example/newsfeed/NewsfeedApplication.java
1. Application 파일에 @EnableJpaAuditing 추가
=> feat: @EnableJpaAuditing 추가

src/main/java/com/example/newsfeed/entity/Comment.java, src/main/java/com/example/newsfeed/entity/Like.java
1. Comment Entity 추가
2. Like Entity 추가
=> feat: Add comment, like entity

src/main/java/com/example/newsfeed/config/WebConfig.java, src/main/java/com/example/newsfeed/entity/BaseEntity.java, src/main/java/com/example/newsfeed/entity/UserEntity.java, src/main/java/com/example/newsfeed/filter/LoginFilter.java
1. dev 브랜치를 pull 해서 로그인 필터를 추가 하였습니다.
2. BaseEntity 에 abstract 를 추가하였습니다.
3. UserEntity 를 추가 하였습니다.
=> feat: Add UserEntity

src/main/java/com/example/newsfeed/entity/User.java
=> fix: Entity name change

src/main/java/com/example/newsfeed/entity/User.java
=> feat: Add Getter

src/main/java/com/example/newsfeed/entity/Board.java
=> feat : Add boardentity

src/main/java/com/example/newsfeed/entity/Comment.java
=> fix: 오타 수정

src/main/java/com/example/newsfeed/entity/User.java
=> feat: Add constructor

src/main/java/com/example/newsfeed/entity/Board.java
=> feat: 오타 수정

src/main/java/com/example/newsfeed/controller/LoginController.java, src/main/java/com/example/newsfeed/controller/UserController.java, src/main/java/com/example/newsfeed/dto/UserLoginRequestDto.java, src/main/java/com/example/newsfeed/service/UserService.java, src/main/java/com/example/newsfeed/service/UserServiceImpl.java
1. UserService 에 메서드를 선언하고 UserServiceImpl 에 @Override 하여 메서드를 구현하도록 수정하였습니다.
=> refactor: UserService 수정

src/main/java/com/example/newsfeed/controller/UserController.java, src/main/java/com/example/newsfeed/dto/UserPatchPasswordRequestDto.java, src/main/java/com/example/newsfeed/entity/User.java, src/main/java/com/example/newsfeed/repository/UserRepository.java, src/main/java/com/example/newsfeed/service/UserService.java, src/main/java/com/example/newsfeed/service/UserServiceImpl.java
=> feat: Add password edit feature

src/main/java/com/example/newsfeed/controller/LoginController.java, src/main/java/com/example/newsfeed/controller/UserController.java, src/main/java/com/example/newsfeed/dto/UserLoginResponseDto.java, src/main/java/com/example/newsfeed/dto/UserSignUpRequestDto.java, src/main/java/com/example/newsfeed/dto/UserSignUpResponseDto.java, src/main/java/com/example/newsfeed/filter/LoginFilter.java, src/main/java/com/example/newsfeed/repository/UserRepository.java, src/main/java/com/example/newsfeed/service/UserService.java, src/main/java/com/example/newsfeed/service/UserServiceImpl.java
=> feat: Add login

src/main/java/com/example/newsfeed/controller/BoardController.java, src/main/java/com/example/newsfeed/dto/BoardResponseDto.java, src/main/java/com/example/newsfeed/dto/CreateBoardRequestDto.java, src/main/java/com/example/newsfeed/repository/BoardRepository.java, src/main/java/com/example/newsfeed/service/BoardService.java
=> feat: 게시물 작성

src/main/java/com/example/newsfeed/service/UserServiceImpl.java
=> fix: 괄호 누락 수정

src/main/java/com/example/newsfeed/controller/UserController.java, src/main/java/com/example/newsfeed/dto/UserPatchInfoRequestDto.java, src/main/java/com/example/newsfeed/entity/User.java, src/main/java/com/example/newsfeed/service/UserService.java, src/main/java/com/example/newsfeed/service/UserServiceImpl.java
=> feat: Add User edit feature

src/main/java/com/example/newsfeed/controller/LoginController.java
=> feat: Add logout

src/main/java/com/example/newsfeed/entity/BaseEntity.java
1. AutoCloseable.class -> AuditingEntityListener.class 로 수정
=> fix: baseentity entitylistener 수정

src/main/java/com/example/newsfeed/controller/UserController.java, src/main/java/com/example/newsfeed/dto/UserLeaveRequestDto.java, src/main/java/com/example/newsfeed/entity/User.java, src/main/java/com/example/newsfeed/service/UserService.java, src/main/java/com/example/newsfeed/service/UserServiceImpl.java
1. 회원탈퇴 시 leave_date 에 LocalDate 를 저장하도록 기능을 추가하였습니다.
=> feat: Add deleteUser

src/main/java/com/example/newsfeed/controller/BoardController.java, src/main/java/com/example/newsfeed/dto/BoardCreateResponseDto.java, src/main/java/com/example/newsfeed/dto/BoardResponseDto.java, src/main/java/com/example/newsfeed/entity/Board.java, src/main/java/com/example/newsfeed/repository/BoardRepository.java, src/main/java/com/example/newsfeed/service/BoardService.java
=> update: 게시물 목록 조회 생성

src/main/java/com/example/newsfeed/controller/BoardController.java, src/main/java/com/example/newsfeed/dto/BoardUpdateRequestDto.java, src/main/java/com/example/newsfeed/dto/BoardUpdateResponseDto.java, src/main/java/com/example/newsfeed/entity/Board.java, src/main/java/com/example/newsfeed/service/BoardService.java
1. 게시글 수정 기능 추가
2. Board 엔티티에 update 메서드 추가
=> feat: 게시글 수정 기능

src/main/java/com/example/newsfeed/controller/BoardController.java, src/main/java/com/example/newsfeed/entity/Likes.java, src/main/java/com/example/newsfeed/repository/LikesRepository.java, src/main/java/com/example/newsfeed/service/BoardService.java
=> feat: Add likes feature

src/main/java/com/example/newsfeed/controller/BoardController.java, src/main/java/com/example/newsfeed/service/BoardService.java
=> feat: Add delete board feature

src/main/java/com/example/newsfeed/entity/Board.java, src/main/java/com/example/newsfeed/service/BoardService.java
=> feat: Add likecount feature

src/main/java/com/example/newsfeed/controller/BoardController.java, src/main/java/com/example/newsfeed/entity/Board.java, src/main/java/com/example/newsfeed/service/BoardService.java
1. 게시글에 댓글이 달려 있을 경우 삭제가 안되는 것을 @OneToMany 로 수정하였습니다.
=> fix: Delete

src/main/java/com/example/newsfeed/controller/UserController.java, src/main/java/com/example/newsfeed/service/UserServiceImpl.java
1. UserController 와 UserServiceImpl 부분에 주석을 추가 하였습니다.
=> style: 유저 부분 주석 추가 및 정렬

src/main/java/com/example/newsfeed/controller/CommentController.java, src/main/java/com/example/newsfeed/controller/FriendController.java, src/main/java/com/example/newsfeed/dto/CommentRequestDto.java, src/main/java/com/example/newsfeed/dto/CommentResponseDto.java, src/main/java/com/example/newsfeed/dto/FriendResponseDto.java, src/main/java/com/example/newsfeed/entity/Comment.java, src/main/java/com/example/newsfeed/entity/Friend.java, src/main/java/com/example/newsfeed/repository/CommentRepository.java, src/main/java/com/example/newsfeed/repository/FriendRepository.java, src/main/java/com/example/newsfeed/service/CommentService.java, src/main/java/com/example/newsfeed/service/FriendService.java
=> refactor: 댓글, 친구 관련 클래스 리팩토링

src/main/java/com/example/newsfeed/entity/BoardLikes.java, src/main/java/com/example/newsfeed/service/BoardService.java
1. 좋아요 카운트 메서드 따로 선언하여 좋아요 업데이트 시에 영향가지 않도록 수정
=> fix: like 기능 추가 수정

src/main/java/com/example/newsfeed/controller/BoardController.java, src/main/java/com/example/newsfeed/service/BoardService.java
1. 게시물 목록 조회 userId 없이 조회되게 코드 변경
2. page 0부터 시작을 1로 변경
=> fix: 코드 수정

build.gradle, src/main/java/com/example/newsfeed/config/PasswordEncoder.java, src/main/java/com/example/newsfeed/controller/UserController.java, src/main/java/com/example/newsfeed/service/UserServiceImpl.java
=> feat: 비밀번호 암호화

src/main/java/com/example/newsfeed/controller/BoardController.java, src/main/java/com/example/newsfeed/repository/BoardRepository.java, src/main/java/com/example/newsfeed/service/BoardService.java
1. 수정일자 순, 좋아요 순, 기간별 조회 기능 구현
=> feat: 정렬 기준 추가

src/main/java/com/example/newsfeed/exception/CustomException.java, src/main/java/com/example/newsfeed/exception/CustomExceptionHandler.java, src/main/java/com/example/newsfeed/exception/ErrorCode.java, src/main/java/com/example/newsfeed/exception/ErrorResponseEntity.java
=> feat: custom exception 추가

src/main/java/com/example/newsfeed/util/ValidationUtils.java
1. BindingResult 객체로 바인딩된 에러 메시지 출력될 수 있도록 수정
=> feat: valid 메시지 출력할 수 있도록 수정

src/main/java/com/example/newsfeed/controller/LoginController.java, src/main/java/com/example/newsfeed/dto/UserLoginRequestDto.java, src/main/java/com/example/newsfeed/service/UserService.java, src/main/java/com/example/newsfeed/service/UserServiceImpl.java
=> feat: 이메일 형식 예외처리

src/main/java/com/example/newsfeed/exception/ErrorCode.java
1. 좋아요 기록을 찾을 수 없는 경우의 404
2. 본인의 글에 좋아요를 누를 때 400
=> feat: 좋아요 관련 ErrorCode 추가

src/main/java/com/example/newsfeed/controller/UserController.java, src/main/java/com/example/newsfeed/exception/ErrorCode.java, src/main/java/com/example/newsfeed/service/UserServiceImpl.java
1. UserController 에 @Valid 를 추가하였습니다.
2. UserServiceImpl 에서 예외처리를 수정하였습니다.
=> feat: User 부분 Valid 추가

src/main/java/com/example/newsfeed/controller/BoardController.java, src/main/java/com/example/newsfeed/exception/ErrorCode.java, src/main/java/com/example/newsfeed/filter/LoginFilter.java, src/main/java/com/example/newsfeed/service/BoardService.java
1. BoardService exception 발생 시 CustomException 으로 출력되도록 수정
2. LoginFilter exception 발생 시 CustomException 으로 출력되도록 수정
=> feat: BoardService, LoginFilter exception 수정

src/main/java/com/example/newsfeed/controller/CommentController.java, src/main/java/com/example/newsfeed/dto/CommentRequestDto.java, src/main/java/com/example/newsfeed/exception/CustomException.java, src/main/java/com/example/newsfeed/exception/ErrorCode.java, src/main/java/com/example/newsfeed/service/CommentService.java, src/main/java/com/example/newsfeed/service/FriendService.java
1. 각 응답 예외가 커스텀 예외를 보내도록 변경
2. CustomException에서 detailMessage가 주어지지 않았을 때 빈칸이 출력되도록 변경
=> feat: 친구, 댓글에 CustomException 적용

src/main/java/com/example/newsfeed/controller/BoardController.java, src/main/java/com/example/newsfeed/controller/UserController.java, src/main/java/com/example/newsfeed/dto/BoardCreateRequestDto.java, src/main/java/com/example/newsfeed/dto/BoardUpdateRequestDto.java, src/main/java/com/example/newsfeed/dto/UserLeaveRequestDto.java, src/main/java/com/example/newsfeed/dto/UserLoginRequestDto.java, src/main/java/com/example/newsfeed/dto/UserSignUpRequestDto.java, src/main/java/com/example/newsfeed/dto/UserUpdateInfoRequestDto.java, src/main/java/com/example/newsfeed/dto/UserUpdatePasswordRequestDto.java, src/main/java/com/example/newsfeed/service/UserServiceImpl.java
1. user, board 관련 valid 추가
2. 비밀번호 비교 시 암호화된 비밀번호로 비교하도록 수정
=> feat: user, board 관련 valid 추가

src/main/java/com/example/newsfeed/controller/UserController.java, src/main/java/com/example/newsfeed/service/UserService.java, src/main/java/com/example/newsfeed/service/UserServiceImpl.java
1. 탈퇴한 유저 로그아웃 처리
2. 로그인 시에 탈퇴한 아이디로 로그인 시도하면 예외처리
=> feat: 탈퇴한 유저 로그아웃 처리

src/main/java/com/example/newsfeed/controller/BoardController.java, src/main/java/com/example/newsfeed/repository/FriendRepository.java, src/main/java/com/example/newsfeed/service/BoardService.java
=> feat: Fix 친구 게시글 조회 코드 수정

src/main/java/com/example/newsfeed/exception/ErrorCode.java, src/main/java/com/example/newsfeed/repository/FriendRepository.java, src/main/java/com/example/newsfeed/service/FriendService.java
1. 친구 요청시 반대의 요청이 있으면 바로 수락
2. 친구 삭제시 반대 테이블도 삭제
=> fix: 친구 요청, 삭제 기능 보완

src/main/java/com/example/newsfeed/controller/CommentController.java, src/main/java/com/example/newsfeed/dto/CommentResponseDto.java, src/main/java/com/example/newsfeed/service/CommentService.java
1. 댓글 수정, 삭제시 권한 확인
2. 댓글 조회시 LikeCount 보이도록 수정
3. 불필요한 import 제거, 코드 줄 맞춤
=> update: 댓글 기능 보완

src/main/java/com/example/newsfeed/controller/UserController.java, src/main/java/com/example/newsfeed/service/UserService.java, src/main/java/com/example/newsfeed/service/UserServiceImpl.java
1.로그인한 유저와 탈퇴하는 유저 확인 하는 로직 추가
=> feat: 로그인한 유저와 탈퇴하는 유저 확인 하는 로직 추가

src/main/java/com/example/newsfeed/entity/Board.java, src/main/java/com/example/newsfeed/service/BoardService.java, src/main/java/com/example/newsfeed/util/HibernateFilterUtil.java
1. 탈퇴한 유저 게시글 목록에서 조회 안되도록 filter 설정
=> feat: 탈퇴한 유저 게시글 목록에서 조회 안되도록 filter 설정
